---
- hosts: devops
  user: gfg
  become: yes
  vars:
    currstate: absent

  tasks:
    - name: Remove HTOP
      action: yum name=htop state='{{ currstate }}' purge=yes

    - name: Remove Git
      action: yum name=git state='{{ currstate }}' purge=yes

    - name: Autoremove unused packages
      action: yum autoremove=yes
